version: "3.9"
services:

  ui:
    build:
      context: ../../ui/
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    env_file:
      - ../../.env-api
      - ../../.env-ui

  api:
    image: xuxinlai2002/issuer:v0.3
    ports:
      - "3003:3001"
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && cd /root/issuer-node/ && ./bin/migrate && ./bin/platform"

  api-ui:
    build:
      context: ../../
      dockerfile: ${DOCKER_FILE}
    ports:
      - "3002:3002"
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && cd /root/issuer-node/ && ./bin/migrate && ./bin/platform_ui"

  notifications:
    build:
      context: ../../
      dockerfile: ${DOCKER_FILE}
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && cd /root/issuer-node && ./bin/notifications"

  pending_publisher:
    image: xuxinlai2002/issuer:v0.3
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && cd /root/issuer-node/ && ./bin/pending_publisher"

  initializer:
    image: xuxinlai2002/issuer:v0.3
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && cd /root/issuer-node/ && ./bin/migrate && ./bin/issuer_initializer"
    # command: sh -c "sleep 4s && ./migrate"

networks:
  default:
      name: issuer-network
